window:
  dimensions:
    columns: 100
    lines: 50

scrolling:
  history: 10000

background_opacity: 1.00

cursor:
  style: Underline
  vi_mode_style: Block
  unfocused_hollow: true
  thickness: 0.25

live_config_reload: false

key_bindings:
  - { key: P,  mods: Alt,                                action: Paste          }
