#! /bin/sh

# Config

bspc config focused_border_color        "$COLOR_NORMAL"
bspc config active_corder_color         "#383838"
bscp config normal_border_color         "#383838"
bspc config presel_border_color         "$COLOR_NOTIFY"
bspc config urgent_border_color         "$COLOR_URGENT"
bspc config focused_locked_border_color "#383838"

bspc config border_width            2
bspc config window_gap              12
bspc config split_ratio             0.50

bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config focus_by_distance       true

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config external_rules_command  "$XDG_CONFIG_HOME/bspwm/rules.sh"

bspc monitor ^1 -d 1 2 3 4 5 6 7 8 9 0

# Autostart

compton --fade-exclude 'name = "panel"' --opacity-rule '85:class_g = "Zathura"' &
sh $XDG_CACHE_HOME/fehbg &
termite --title=vim -e "/usr/bin/nvim -S $XDG_CACHE_HOME/nvim/session.vim" & disown
gloom -c -k "i3lock-fancy -pf M+-1m-regular" &
xset r rate 200 25 &
redshift &
multihead &
