#!/bin/bash

# Only supports up to 3 monitors!

source $XDG_CONFIG_HOME/zsh/.zprofile

declare -A monitor
primary=''
icons=(${DESKTOP_ICONS//:/ })
urg='%{F'$COLOR_URGENT'}'
cur='%{F'$COLOR_NOTIFY'}'
occ='%{F#383838}'
res='%{F-}'

setup_monitors() {
    output=$(xrandr)
    layouts=(${MONITOR_LAYOUTS//:/ })
    desktops=(5 6 7 8 9 0)
    optimal_res=($(grep -zoP '(?s)\ connected.*?\s{2,}\K\w+\s' <<< "$output"))
    screen_name=($(grep -oP '^\w+(?=\ (dis)?connected)' <<< "$output"))
    connections=($(grep -oP '(dis)?connected' <<< "$output"))
    primary=${screen_name[0]}

    conns=1
    xrandr --output $primary --mode ${optimal_res[0]}
    bspc monitor $primary -d 1 2 3 4

    for num in ${!screen_name[*]}
    do
        # skip the primary monitor, and any connected monitor over 3
        [ $num -eq 0 ] || [ $conns -ge 3 ] && continue
        if [ "${connections[$num]}" == "connected" ]; then
            xrandr --output ${screen_name[$num]} ${layouts[$((conns-1))]} $primary --mode ${optimal_res[$conns]}
            bspc monitor ${screen_name[$num]} -d ${desktops[@]:$(((conns-1)*3)):${#desktops[@]}}
            ((conns++))
        else
            xrandr --output ${screen_name[$num]} --off
        fi
    done

    [ $conns -eq 1 ] &&
        bspc monitor $primary -d 1 2 3 4 ${desktops[@]}
}

#setup_monitors
sleep 2

while read line; do

    case $line in
        # bspc
        W*)
            wm=""
            dtop=1
            desktops=($(grep -oP '(?<=:)([a-zA-Z](Desktop)?[0-9])|LT(?=:)' <<< "$line"))
            datetime=$(date "+%h %d, %I:%M%P")

            for desktop in ${desktops[@]}
            do
                icon=${icons[$(($dtop - 1))]}

                case $desktop in
                    "o"*) wm+="$occ  $icon  $res";;
                    "O"*|"F"*)
                        [ ${#monitor[@]} -gt 1 ] && [[ ${desktop:1} == $(bspc query -D -d) ]] &&
                            wm+="${cur} $icon ${res}" ||
                            wm+="${cur}  $icon  ${res}"
                        ;;
                    "u"*|"U"*)
                        wm+="$urg  $icon  $res"
                        wm show panel
                        ;;
                    "L"*)
                        [ ${#monitor[@]} -gt 1 ] &&
                            wm+="%{O25}"
                            dtop=$(($dtop - 1))
                esac
                dtop=$(($dtop + 1))
            done
            ;;
        #conky
        c*)
            stat=$(cut -c 2- <<< "$line" | sed -e "s/!!/%{F$COLOR_URGENT}/g" -e "s/!-/%{F-}/g")
            ;;
        t*)
            clock=$(cut -c 2- <<< "$line")
            ;;
    esac

    l="%{l} $stat"
    c="%{c} $wm "
    r="%{r}%{F-}$clock  "
    printf "%s\n" "$l$c$r"

done < <(bspc subscribe & conky -c $XDG_CONFIG_HOME/conky/status.conf & conky -c $XDG_CONFIG_HOME/conky/time.conf)\
    | lemonbar -g 900x18 -p -f "$FONT_ICON-10" -f "$FONT_MONO-7" -B $COLOR_NORMAL -F "#000" -n "panel"
