#!/bin/bash

source $XDG_CONFIG_HOME/zsh/.zprofile
sleep 2

monitors=$(bspc query -M | wc -l)
icons=(${DESKTOP_ICONS//:/ })
urg='%{F'$COLOR_URGENT'}'
cur='%{F'$COLOR_NOTIFY'}'
occ='%{F#383838}'
res='%{F-}'

while read line; do

    case $line in
        # bspc
        W*)
            wm=""
            dtop=1
            desktops=($(grep -oP '(?<=:)([a-zA-Z](Desktop)?[0-9])|LT(?=:)' <<< "$line"))
            datetime=$(date "+%h %d, %I:%M%P")

            for desktop in ${desktops[@]}
            do
                icon=${icons[$(($dtop - 1))]}

                case $desktop in
                    "o"*) wm+="$occ  $icon  $res";;
                    "O"*|"F"*)
                        [[ $monitors -gt 1 ]] && [[ ${desktop:1} == $(bspc query -D -d) ]] &&
                            wm+="${cur} $icon ${res}" ||
                            wm+="${cur}  $icon  ${res}"
                        ;;
                    "u"*|"U"*)
                        wm+="$urg  $icon  $res"
                        wm show panel
                        ;;
                    "L"*)
                        [[ $monitors -gt 1 ]] &&
                            wm+="%{O25}"
                            dtop=$(($dtop - 1))
                esac
                dtop=$(($dtop + 1))
            done
            ;;
        #conky
        c*)
            stat=$(cut -c 2- <<< "$line" | sed -e "s/!!/%{F$COLOR_URGENT}/g" -e "s/!-/%{F-}/g")
            ;;
        t*)
            clock=$(cut -c 2- <<< "$line")
            ;;
    esac

    left="%{l} $stat"
    center="%{c} $wm "
    right="%{r}%{F-}$clock  "
    printf "%s\n" "$left$center$right"

done < <(\
    bspc subscribe & \
    conky -c $XDG_CONFIG_HOME/conky/status.conf & \
    conky -c $XDG_CONFIG_HOME/conky/time.conf \
) | lemonbar -g $(flap -w 900 -h 18 -x c -y t "%wx%h+%x+%y") -p -f "$FONT_ICON-10" -f "$FONT_MONO-7" -B $COLOR_NORMAL -F "#000" -n "panel"
#) | lemonbar -g $PANEL_SIZE -p -f "$FONT_ICON-10" -f "$FONT_MONO-7" -B $COLOR_NORMAL -F "#000" -n "panel"
