#!/bin/bash

# ugly but works
cat $XDG_CONFIG_HOME/sway/template | sed 's/#000000/'"$COLOR_DARK"'/g; s/#888888/'"$COLOR_MEDIUM"'/g; s/#FFFFFF/'"$COLOR_LIGHT"'/g; s/#FF0000/'"$COLOR_ACCENT"'/g;' > $XDG_RUNTIME_DIR/swayconfig

exec i3 -c $XDG_RUNTIME_DIR/swayconfig
