" Auto install Plug
if empty(glob('$XDG_CONFIG_HOME/nvim/autoload/plug.vim'))
    silent !curl -fLo $XDG_CONFIG_HOME/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall
endif

if empty(glob('$XDG_CONFIG_HOME/nvim/spell'))
    silent ! mkdir $XDG_CONFIG_HOME/nvim/spell > /dev/null
endif

" If GUI Version
if has('gui_running')
    set guioptions-=m
    set guioptions-=T
    set guioptions-=r
    set guioptions-=L
    au GUIEnter * simalt ~x
endif

" ========== OPTIONS ==========

set hidden
set noshowmode
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set number
set noswapfile
set cursorline
set ttyfast
set lazyredraw
set t_Co=256
set encoding=utf-8
set clipboard=unnamedplus
set breakindent
set linebreak
set directory=$XDG_CACHE_HOME/nvim,.
set backupdir=$XDG_CACHE_HOME/nvim,.
set viminfo+=n$XDG_CACHE_HOME/nvim/nviminfo
set runtimepath=$XDG_CONFIG_HOME/nvim,$VIM,$VIMRUNTIME
set wildcharm=<Tab>
set wildmenu
set wildmode=full,list
set wildignorecase

let $MYVIMRC="$XDG_CONFIG_HOME/nvim/nvimrc"
let $PAGER=""

syntax on
filetype plugin indent on
let mapleader = "\<Space>"
:runtime! ftplugin/man.vim

" ========== PACKAGES ==========

call plug#begin('$XDG_CONFIG_HOME/nvim/plugged')

" Buffer Management
Plug 'moll/vim-bbye'

" Looks
Plug 'tomasr/molokai'
Plug 'bling/vim-airline'
"Plug 'itchyny/lightline.vim'
Plug 'airblade/vim-gitgutter'

" Interaction
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'godlygeek/tabular'

" Utility
Plug 'tpope/vim-fugitive'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate'

" Syntax & Highlighting
Plug 'scrooloose/syntastic'
Plug 'jelera/vim-javascript-syntax'
Plug 'pangloss/vim-javascript'
Plug 'wavded/vim-stylus'
Plug 'digitaltoad/vim-jade'
Plug 'plasticboy/vim-markdown'
Plug 'rust-lang/rust.vim'

call plug#end()

" ========== SETTINGS ==========

" Molokai
color molokai
let g:molokai_original = 1
let g:rehash256 = 1

" Airline
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_detect_crypt = 0
"let g:airline#extensions#tabline#enabled = 1
let g:airline_theme = 'shizy'
let g:airline_symbols.whitespace = ''
let g:airline_left_sep = ''
let g:airline_right_sep = ''
"let g:airline#extensions#tabline#show_tab_type = 0
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''
let g:airline#extensions#whitespace#trailing_format = '  %s'

" Sessions
function! Save()
    if empty(glob('$XDG_CACHE_HOME/nvim'))
        silent ! mkdir $XDG_CACHE_HOME/nvim > /dev/null
    endif
    :mks! $XDG_CACHE_HOME/nvim/session.vim
    :w
endfunction

" Multi Cursor
let g:multi_cursor_next_key = '<S-s>'
let g:multi_cursor_skip_key = 's'

" Git-Gutter
let g:gitgutter_realtime = 0
let g:gitgutter_eager = 0

" LaTeX
source $XDG_CONFIG_HOME/nvim/latex.vim

" Syntastic
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_aggregate_errors = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" ========== MAPPINGS ==========

noremap             <A-j>           10j
noremap             <A-k>           10k

nnoremap            <A-l>           e
nnoremap            <A-h>           b
nnoremap            <A-S-l>         $
nnoremap            <A-S-h>         ^
nnoremap            <A-S-j>         G
nnoremap            <A-S-k>         gg
nnoremap            <A-b>           :b#<CR>
nnoremap            <A-w>           <C-w>p
nnoremap            <A-z>           :call Save()<CR>:qa<CR>
nnoremap            <A-u>           <C-r>
nnoremap            <A-Tab>         <C-w>w
nnoremap            <A-S-Tab>       <C-w>W
nnoremap            <A-Left>        :vertical resize -10<CR>
nnoremap            <A-Right>       :vertical resize +10<CR>
nnoremap            <A-Up>          :resize -10<CR>
nnoremap            <A-Down>        :resize +10<CR>
nnoremap            <A-/>           :noh<CR>
nnoremap            <A-.>           :lnext<CR>
nnoremap            <A-,>           :lprev<CR>
nnoremap <silent>   <Leader><Space> @=(foldlevel('.')?'za':"\<Space>")<CR>
nmap                <A-Space>       :ls<CR>:b<Space><Tab><C-p>
nmap                <A-s>           :ls<CR>:sb<Space><Tab><C-p>
nmap                <A-v>           :ls<CR>:vert:sb<Space><Tab><C-p>
nmap                <A-x>           :ls<CR>:Bdelete!<Space><Tab><C-p>
nmap                <A-S-x>         :Bdelete!<CR>
nmap                <A-q>           ZZ
nmap                <Leader>w       :call Save()<CR>
nmap                <Leader>1       :w !sudo tee % > /dev/null
nmap                <Leader>/       <Esc>:%s/
nmap                <Leader>t       :Tabularize /
nmap                <Leader>s       :Gstatus<CR><C-n>
nmap                <Leader>p       :Gpush<space>
nmap                <Leader>u       :PlugUpdate<CR>
nmap                <Leader>e       :e %:h<Tab><Tab><C-p>

imap                jj              <Esc>
imap                jk              <Esc>:call Save()<CR>

cmap                <A-l>           <C-n>
cmap                <A-h>           <C-p>
cmap                <A-j>           <Down>
cmap                <A-k>           <Up>
cmap                jj              <C-c><Esc>
cmap                <A-Space>       <C-c><Esc>
cmap                jk              <CR>

tnoremap            <A-Tab>         <C-\><C-n><C-w>w
tnoremap            <A-S-Tab>       <C-\><C-n><C-w>W

vnoremap            <Leader><Space> zf
vmap                <Leader>/       <Esc>:'<,'>s/
vmap                <Leader>t       :Tabularize /
vmap                <A-,>           <gv
vmap                <A-.>           >gv


" ========== AUTOCOMMANDS ==========

au BufNewFile,BufRead *.styl set filetype=stylus
au BufNewFile,BufRead *.ejs  set filetype=js
au BufNewFile,BufRead *.ejs  set filetype=html
au BufNewFile,BufRead,BufWinEnter *.tex
    \ setlocal spell |
    \ setlocal spelllang=en_us |
    \ setlocal nocin inde= |
    \ set syntax=tex |
    \ nnoremap <buffer> <Leader>l :call LatexMake()<CR> |
    \ nnoremap <buffer> <Leader>x :call LatexPreviewClose()<CR> |
    \ nnoremap <buffer> <A-.>      ]s |
    \ nnoremap <buffer> <A-,>      [s
au CursorMoved *.tex :call LatexUpdate()
au BufWinEnter *.tex :call LatexPreviewShow()
au BufWinLeave *.tex :call LatexPreviewHide()
au BufNewFile,BufRead,BufWinEnter ~/.cache/mutt/*
    \ setlocal spell |
    \ setlocal spelllang=en_us |
    \ setlocal nonumber |
    \ set syntax=markdown |
    \ setlocal fo+=aw |
    \ imap <buffer> jk <Esc>:w<CR> |
    \ nmap <buffer> <Leader>w :w<CR> |
au FileType gitcommit
    \ nmap <buffer> <A-.>   <C-n> |
    \ nmap <buffer> <A-,>   <C-p> |
    \ nmap <buffer> c       <S-c>i |
    \ nmap <buffer> q       :wq<CR> |
    \ nmap <buffer> p       :wq<CR>:Gpush<space> |
au BufWinEnter *.md set syntax=markdown
au BufWinEnter *.toml set filetype=toml
au FileType netrw nmap <buffer> <Esc> :bd<CR>
au WinEnter term://* startinsert
au FileType help
    \ set ro |
    \ nnoremap <buffer> <CR> <C-]> |
    \ nnoremap <buffer> f    <C-]> |
    \ nnoremap <buffer> u    <C-T> |
au FileType man
    \ set ro |
    \ set nolist |
    \ nnoremap <buffer> <CR>        :call <SNR>8_PreGetPage(v:count)<CR> |
    \ nnoremap <buffer> f           :call <SNR>8_PreGetPage(v:count)<CR> |
    \ nnoremap <buffer> u           :call <SNR>8_PopPage()<CR> |
    \ nnoremap <buffer> <A-z>       :q<CR> |
    \ nnoremap <buffer> <Leader>w   <NOP> |
    \ nnoremap <buffer> -           <NOP>

" Color & theme over-rides
source $XDG_CONFIG_HOME/nvim/theme-overrides.vim
